server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8083
          predicates:
            - Path=/users/**
        - id: book-service
          uri: http://book-service:8084
          predicates:
            - Path=/books/**
        - id: reviews-service
          uri: http://reviews-service:8085
          predicates:
            - Path=/reviews/**

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: INFO
