server:
  port: 8086

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENTID}
            client-secret: ${GOOGLE_CLIENTSECRET}
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8083
          predicates:
            - Path=/users/**
        - id: book-service
          uri: http://book-service:8084
          predicates:
            - Path=/books/**
        - id: reviews-service
          uri: http://reviews-service:8085
          predicates:
            - Path=/reviews/**


